Cora:
  seed: 39788
  learning_rate: 0.0005
  weight_decay: 0.00001
  num_epochs: 5000
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.4 
  feature_drop_rate_rdm: 0.3 
  edge_drop_ub_aug: 0.8
  edge_drop_rate_rdm: 0.2
  gen_ub: False
  dis_lambda: 0 #0.00001
  tau: 0.4
CiteSeer:
  seed: 23344 #38108
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 1000
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.3
  feature_drop_rate_rdm: 0.2
  edge_drop_ub_aug: 0.2 #0.8
  edge_drop_rate_rdm: 0.0
  gen_ub: False
  dis_lambda: 0 #0.00001
  tau: 0.9
PubMed:
  seed: 23344
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 3000
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.1
  feature_drop_rate_rdm: 0.1
  edge_drop_ub_aug: 0.3 #0.4
  edge_drop_rate_rdm: 0.5
  gen_ub: False
  dis_lambda: 10
  tau: 0.4
AmazonPhoto:
  seed: 23344
  learning_rate: 0.01 
  weight_decay: 0.00001
  num_epochs: 6000
  num_hidden: 256
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.1
  feature_drop_rate_rdm: 0.1
  edge_drop_ub_aug: 0.95 #0.5
  edge_drop_rate_rdm: 0.3
  gen_ub: False
  dis_lambda: 60
  tau: 0.3
AmazonCom:
  seed: 23344
  learning_rate: 0.01
  weight_decay: 0.00001
  num_epochs: 3000
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'rrelu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.2
  feature_drop_rate_rdm: 0.3
  edge_drop_ub_aug: 0.9 #0.6
  edge_drop_rate_rdm: 0.3
  gen_ub: False
  dis_lambda: 0 #0.5
  tau: 0.2
CoauthorCS:
  seed: 23344
  learning_rate: 0.0005
  weight_decay: 0.00001
  num_epochs: 3000
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'rrelu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.3
  feature_drop_rate_rdm: 0.4
  edge_drop_ub_aug: 0.3 
  edge_drop_rate_rdm: 0.2
  gen_ub: False
  dis_lambda: 0.00001
  tau: 0.4
Coauthorphy:
  seed: 23344
  learning_rate: 0.01
  weight_decay: 0.00001
  num_epochs: 5000
  num_hidden: 128
  num_proj_hidden: 64
  activation: 'rrelu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.1
  feature_drop_rate_rdm: 0.4
  edge_drop_ub_aug: 0.4
  edge_drop_rate_rdm: 0.1
  gen_ub: False
  dis_lambda: 10
  tau: 0.5
WikiCS:
  seed: 23344
  learning_rate: 0.001
  weight_decay: 0.00001
  num_epochs: 5000
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: True
  feature_drop_ub_aug: 0.1
  feature_drop_rate_rdm: 0.1
  edge_drop_ub_aug: 0.8
  edge_drop_rate_rdm: 0.3
  gen_ub: False
  dis_lambda: 50 #10
  tau: 0.4
ogbn-arxiv:
  seed: 39788
  learning_rate: 0.0005
  weight_decay: 0.00001
  num_epochs: 5000
  num_hidden: 128
  num_proj_hidden: 2
  activation: 'relu'
  base_model: 'gcn'
  num_layers: 2
  gen_type: 'edge'
  gen_in_epoch: False
  feature_drop_ub_aug: 0.4 
  feature_drop_rate_rdm: 0.3 
  edge_drop_ub_aug: 0.8
  edge_drop_rate_rdm: 0.2
  gen_ub: False
  dis_lambda: 0 #0.00001
  tau: 0.4